[workspace]
members = ["projects/*"]
default-members = [
    "projects/gg-error",
    "projects/gg-plot",
    "projects/gg-rust",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
